### ISSUE TITLE
Add hard limits for operation and event sizes

### ISSUE THREAD

**Issue by dlongley** [veres-one/veres-one-validator#3]

**Comment by mattcollier** [comment]
We implemented size restrictions on operation sizes in Continuity here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/events.js#L771-L781

Is there anything here to be done related to this?

**Comment by dlongley** [comment]
@mattcollier,

> Is there anything here to be done related to this?

Is there a hard limit on the number of operations per event as well? If not, we need to close that loop as well.

**Comment by mattcollier** [comment]
Yes, there is a hard coded limit of 250 operations per event: 
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/continuityConstants.js#L11-L24

**Comment by dlongley** [comment]
@mattcollier --- then we're done here.

**Comment by dlongley** [comment]
Thanks!
